Bot:
    Token: ""
    AllowedIds: [222, 123]

Proxies:
  # http and https
  HTTP: [
    'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt', 
    'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt',
    'https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all',
    'https://www.proxy-list.download/api/v1/get?type=http',
    'https://raw.githubusercontent.com/saisuiu/uiu/main/free.txt',
    'https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt', 
    'https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt', 
    'https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt', 
    'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt', 
    'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt']
  SOCKS5: [
    'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt',
    'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt',
    'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt',
    'https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5&timeout=10000&country=all&ssl=all&anonymity=all'

  ]
  SOCKS4: [
    'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt',
    'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt',
    'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt',
    'https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4&timeout=10000&country=all&ssl=all&anonymity=all',

  ]